name: pub

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install cowsay

      - name: Run cowsay
        run: cowsay "Hello, world!"

      - name: Run cowsay with reza
        run: cowsay "hi reza" >> $GITHUB_STEP_SUMMARY

      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Add summary using JavaScript
        run: |
          echo "const core = require('@actions/core');" > summary.js
          echo "const generateTestResults = () => {" >> summary.js
          echo "  return 'foo.js: Pass ✅\\nbar.js: Fail ❌\\ntest.js: Pass ✅';" >> summary.js
          echo "};" >> summary.js
          echo "core.summary" >> summary.js
          echo "  .addHeading('Test Results')" >> summary.js
          echo "  .addCodeBlock(generateTestResults(), 'js')" >> summary.js
          echo "  .addTable([['File', 'Result'], ['foo.js', 'Pass ✅'], ['bar.js', 'Fail ❌'], ['test.js', 'Pass ✅']])" >> summary.js
          echo "  .addLink('View staging deployment!', 'https://github.com')" >> summary.js
          echo "  .write();" >> summary.js
          node summary.js
